version: '3.8'

services:
  app:
    build: .
    container_name: travel-collab-app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment: 
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: travel_db
      DB_USERNAME: user
      DB_PASSWORD: userpassword
      SESSION_SECRET: docker_secret
      REDIS_HOST: redis 
      REDIS_PORT: 6379
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - travel-net

  db:
    image: mysql:8.0
    container_name: travel-collab-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: travel_db
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - travel-net

  redis:
    image: redis:7.2
    container_name: travel-collab-redis
    ports:
      - "6379:6379"
    networks:
      - travel-net

volumes:
  mysql_data:

networks:
  travel-net:
