name: Run Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Create SQLite DB folder
        run: mkdir -p db

      - name: Clean old test DB
        run: rm -f db/test.sqlite

      - name: Run migrations
        run: npx sequelize-cli db:migrate --env test

      - name: Run seeders
        run: npx sequelize-cli db:seed:all --env test

      - name: Run Tests
        run: npm test